# cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tweethardenft
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tweet
            image: "hardenft:v1"
          restartPolicy: OnFailure