# cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tweethardenft
spec:
  schedule: "28 17 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tweet
            image: hardenft
          restartPolicy: OnFailure